Update bf-pldm-ver

diff --git a/scripts/bf-pldm-ver b/scripts/bf-pldm-ver
--- a/scripts/bf-pldm-ver
+++ b/scripts/bf-pldm-ver
@@ -28,14 +28,21 @@ usage() {
     Usage: $(basename $0) <pldm-image-file>
 EOF
 }
+#cleanup
+cleanup() {
+    # Remove the temp directory.
+    rm -rf $TMP_DIR
+}
 
 if [ $# -lt 1 ]; then
     echo "Error: $(basename $0) requires 1 argument."
     exit 1
 fi
 
-if [ ! -e "$1" ]; then
-    echo "Error: $1 file not found."
+pldm_image_file=$1
+
+if [ ! -e "$pldm_image_file" ]; then
+    echo "Error: $pldm_image_file file not found."
     exit 1
 fi
 
@@ -46,11 +53,20 @@ if [ ! -d "${TMP_DIR}" ]; then
     exit 1
 fi
 
+trap cleanup EXIT INT TERM
+
 # NIC FW & BSP
 fwpkg_unpack.py --show_all_metadata --verbose $1 | grep "ComponentVersionString\"" | awk 'BEGIN { product[1] = "BlueField NICFW version: "; product[2] = "BlueField BSP   version: ";} {print product[NR] $2}' | tr -d '"' 
+if [ ! $? -eq 0 ]; then
+    echo "Error: failed to get NICFW version."
+fi
 
 # Unpack
 fwpkg_unpack.py --unpack --outdir ${TMP_DIR} $1 
+if [ ! $? -eq 0 ]; then
+    echo "Error: failed to unpack $pldm_image_file."
+    exit 1
+fi
 
 # UEFI
 print_capsule_file_vers () {
@@ -117,9 +133,13 @@ done
 # BMC & CEC
 for file in ${TMP_DIR}/dump*; do
     fwpkg_unpack.py --show_all_metadata --verbose $file  | grep "ComponentVersionString\"" | awk -v substrBMC="ApFw" -v substrCEC="Ecfw" '{ if (index($2, substrBMC)) {print "BlueField BMC   version: " $2} else if (index($2, substrCEC)) { print "BlueField CEC   version: " $2}}' | tr -d '"'
+
+    if [ ! $? -eq 0 ]; then
+        echo "Error: failed to read $file."
+        exit 1
+    fi
 done
 
 popd > /dev/null
 
-#cleanup
-rm -rf ${TMP_DIR}
+exit 0
