bfb-install: add validation of bfb file is exist
Add the check if the input bfb file exists.

RM #4551986

Signed-off-by: Dong Zhou <dongzhou@nvidia.com>

diff --git a/scripts/bfb-install b/scripts/bfb-install
--- a/scripts/bfb-install
+++ b/scripts/bfb-install
@@ -676,6 +676,12 @@ if [ -n "${bfb}" -a -n "${pldm}" ]; then
   exit 1
 fi
 
+# Check if bfb file exists.
+if [ -n "${bfb}" -a ! -e "${bfb}" ]; then
+  echo "Error: ${bfb} not found."
+  exit 1
+fi
+
 # Check if bfb and rshim are set and non-empty
 if [ -z "${rshim}" ]; then
   echo "Error: Need to provide rshim device name."
