bfb-install: register usage cleanup
This commits check chip version to define the register
offsets instead of using hardcoded value. So the same
script could work for both BF2 and BF3.

Signed-off-by: Liming Sun <limings@nvidia.com>

diff --git a/scripts/bfb-install b/scripts/bfb-install
--- a/scripts/bfb-install
+++ b/scripts/bfb-install
@@ -39,6 +39,13 @@ LOG_FILE="/tmp/bfb-install.log"
 run_cmd_local_ready=0     # whether run_cmd* local functions are ready to use
 run_cmd_remote_ready=0    # whether run_cmd* remote functions are ready to use
 
+# Register definition (BF3 by default).
+RSH_BOOT_FIFO_COUNT=0x13001000
+RSH_BOOT_FIFO_DATA=0x13002000
+RSH_SCRATCHPAD2=0x13000c48
+RSH_SWINT=0x13000318
+RSH_BREADCRUMB1=0x13000518
+
 usage ()
 {
   echo "Usage: $0 [options]"
@@ -179,16 +186,18 @@ clear_boot_fifo()
 
   while true; do
     # Read BOOT_FIFO_DATA if BOOT_FIFO_COUNT != 0
-    cnt=`${BF_REG} $(basename ${rshim_node}) 0x13001000.64 | awk '{print $3}'`
+    cnt=`${BF_REG} $(basename ${rshim_node}) ${RSH_BOOT_FIFO_COUNT}.64 | awk '{print $3}'`
     cnt=$((cnt))
     [ $cnt -eq 0 ] && break
-    ${BF_REG} $(basename ${rshim_node}) 0x13002000.64 >/dev/null
+    ${BF_REG} $(basename ${rshim_node}) ${RSH_BOOT_FIFO_DATA}.64 >/dev/null
   done
 }
 
 # Push the boot stream to rshim via local rshim
 push_boot_stream_via_local_rshim()
 {
+  local sp2
+
   # Push the boot stream to local rshim
   echo "Pushing bfb${cfg:+ + cfg}${rootfs:+ + rootfs}"
 
@@ -200,11 +209,13 @@ push_boot_stream_via_local_rshim()
     clear_boot_fifo
 
     # Set SP2.BIT2=1
-    ${BF_REG} $(basename ${rshim_node}) 0x13000c48.64 0x4 >/dev/null
+    sp2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 | awk '{print $3}'`
+    sp2=$((sp2 | 4))
+    ${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 $sp2 >/dev/null
 
     # Set SWINT2.BIT2 for DPU mode
     if [ ${nic_mode} -eq 0 ]; then
-      ${BF_REG} $(basename ${rshim_node}) 0x13000318.64 0x4 >/dev/null
+      ${BF_REG} $(basename ${rshim_node}) ${RSH_SWINT}.64 0x4 >/dev/null
     fi
   fi
 
@@ -509,9 +520,28 @@ wait_for_update_to_finish()
   run_cmd_exit $mode "echo 'CLEAR_ON_READ 0' > ${rshim_node}/misc"
 }
 
+apply_chip_settings()
+{
+  local chip
+
+  chip=$(run_cmd_exit $mode "cat ${rshim_node}/misc | grep DEV_INFO")
+  chip=$(echo "${chip}" | awk '{print $2}')
+  chip=${chip:0:11}
+
+  if [ ."${chip}" == ."BlueField-1" -o ."${chip}" == ."BlueField-2" ]; then
+    RSH_BOOT_FIFO_COUNT=0x00010488
+    RSH_BOOT_FIFO_DATA=0x00010408
+    RSH_SCRATCHPAD2=0x00010c28
+    RSH_SWINT=0x00010318
+    RSH_BREADCRUMB1=0x00010518
+  fi
+}
+
 # Clean up function whenever the script exits
 # shellcheck disable=SC2317
 cleanup() {
+  local sp2
+
   # prevent cleanup from being called multiple times
   if [ "$cleanup_started" -eq 1 ]; then
     exit 1
@@ -540,13 +570,13 @@ cleanup() {
     echo "BOOT_RESET_SKIP 0" > ${rshim_node}/misc
 
     # Cleanup SP2.BIT2.
-    sp2=`${BF_REG} $(basename ${rshim_node}) 0x13000c48.64 | awk '{print $3}'`
+    sp2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 | awk '{print $3}'`
     sp2=$((sp2 & ~4))
-    ${BF_REG} $(basename ${rshim_node}) 0x13000c48.64 $sp2 >/dev/null
+    ${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 $sp2 >/dev/null
 
     # Set SWINT2.BIT2 for DPU mode
     if [ ${nic_mode} -eq 0 ]; then
-      ${BF_REG} $(basename ${rshim_node}) 0x13000318.64 0x4 >/dev/null
+      ${BF_REG} $(basename ${rshim_node}) ${RSH_SWINT}.64 0x4 >/dev/null
     fi
   fi
 
@@ -695,6 +725,11 @@ if [ $mode == "local" ] && [ -n "$remote_mode" ]; then
 fi
 
 if [ $mode == "remote" ] ; then
+  if [ $runtime -eq 1 ]; then
+    echo "Error: runtime upgrade is only supported for local rshim."
+    exit 1
+  fi
+
   # convert potential host name to IP address
   ip=$(getent ahosts $ip | awk '{print $1}' | head -n 1)
 
@@ -891,23 +926,26 @@ if [ $mode == "remote" ]; then
         "Error: local netcat port $port is not available"
     fi
   fi
-
 fi
 
+# Check the pv tool.
 pv=$(which pv 2>/dev/null)
 if [ -z "${pv}" ]; then
   echo "Warn: 'pv' command not found. Continue without showing BFB progress."
 fi
+
+# Check BF chip version and adjust register offsets.
+apply_chip_settings
 
 # Check NIC mode and unbind mlx5_core driver in NIC mode.
 check_nic_mode
 
 if [ ${nic_mode} -eq 1 -a -n "${pcie_bd}" -a ${runtime} -eq 0 ]; then
   # Set BREADCRUMB.BIT32 to indicate NIC mode.
-  breadcrumb1=$(${BF_REG} $(basename ${rshim_node}) 0x13000518.64 | awk '{print $3}')
+  breadcrumb1=$(${BF_REG} $(basename ${rshim_node}) ${RSH_BREADCRUMB1}.64 | awk '{print $3}')
   breadcrumb1=$((breadcrumb1 | (0x1 << 32)))
   breadcrumb1=$(printf "0x%x\n" $breadcrumb1)
-  ${BF_REG} $(basename ${rshim_node}) 0x13000518.64 ${breadcrumb1} >/dev/null
+  ${BF_REG} $(basename ${rshim_node}) ${RSH_BREADCRUMB1}.64 ${breadcrumb1} >/dev/null
 
   for i in 0 1; do
     if [[ ! -e /sys/bus/pci/drivers/mlx5_core/${pcie_bd}.${i} ]]; then
