RM #4699482 RM #4701897 RM #4691408 RM #4690152

diff --git a/scripts/bfb-install b/scripts/bfb-install
--- a/scripts/bfb-install
+++ b/scripts/bfb-install
@@ -192,6 +192,22 @@ clear_boot_fifo()
   done
 }
 
+clear_sp2_267_swint2_2()
+{
+  sp2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 | awk '{print $3}'`
+
+  # reset SP2.BIT2|6|7  4 + 64 + 128 = 196
+  sp2=$((sp2 & ~196))
+  ${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 $sp2 >/dev/null
+
+  # reset SWINT2.BIT2 for DPU mode
+  sw2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SWINT2}.64 | awk '{print $3}'`
+  if [ ${nic_mode} -eq 0 & $sw2 -ne 0 ] ; then
+    ${BF_REG} $(basename ${rshim_node}) ${RSH_SWINT2}.64 0x0 >/dev/null
+  fi
+  sleep 1
+}
+
 # Push the boot stream to rshim via local rshim
 push_boot_stream_via_local_rshim()
 {
@@ -206,10 +222,12 @@ push_boot_stream_via_local_rshim()
 
     # Clear the current boot fifo
     clear_boot_fifo
+    clear_sp2_267_swint2_2
 
     # Set SP2.BIT2=1
     sp2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 | awk '{print $3}'`
     sp2=$((sp2 | 4))
+    echo "SP2 $sp2"
     ${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 $sp2 >/dev/null
 
     # Set SWINT2.BIT2 for DPU mode
@@ -396,8 +414,8 @@ push_boot_stream()
   fi
 }
 
-# Checks BF3 NIC_MODE
-check_nic_mode()
+# pcie_bd is needed by check_nic_mode and other places. Shall be called eary
+check_pcie_bdf()
 {
   local str
 
@@ -412,6 +430,19 @@ check_nic_mode()
   str=${str:5}
   str=${str/.*/}
   pcie_bd="$str"
+}
+
+# Checks BF3 NIC_MODE
+check_nic_mode()
+{
+  local str
+
+  [ "$mode" != "local" ] && return
+
+  # Only needs to check for BF3.
+  str=`cat ${rshim_node}/misc | grep DEV_INFO | grep BlueField-3`
+  [ -z "$str" ] && return
+
   num_ports=$(lspci -nn -s $pcie_bd | grep -v '\[0801\]' | wc -l || { echo "Failed to query PCIe ports for $pcie_bd"; echo 0; })
   if [ "$num_ports" -eq 2 ]; then
     [ $verbose -eq 1 ] && echo "Detected dual-port device: ${pcie_bd}.0 and ${pcie_bd}.1"
@@ -537,7 +568,6 @@ apply_chip_settings()
 # Clean up function whenever the script exits
 # shellcheck disable=SC2317
 cleanup() {
-  local sp2
 
   # Remove the temp directory.
   rm -rf $TMP_DIR
@@ -569,14 +599,7 @@ cleanup() {
     # Reset to default state.
     echo "BOOT_RESET_SKIP 0" > ${rshim_node}/misc
 
-    # Cleanup SP2.BIT2.
-    sp2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 | awk '{print $3}'`
-    sp2=$((sp2 & ~4))
-    ${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 $sp2 >/dev/null
-    # Set SWINT2.BIT2 for DPU mode
-    if [ ${nic_mode} -eq 0 ]; then
-      ${BF_REG} $(basename ${rshim_node}) ${RSH_SWINT}.64 0x4 >/dev/null
-    fi
+    clear_sp2_267_swint2_2
   fi
 
   # Disable CLEAR_ON_READ.
@@ -823,6 +846,7 @@ run_cmd_local_ready=1
 
 # Setup checks
 
+check_pcie_bdf
 
 # Check PLDM and convert it into BFB.
 if [ -n "${pldm}" ]; then
@@ -918,6 +942,21 @@ elif [ ${deferred} -eq 1 -a -e "${bfb}" ]; then
       mlx-mkbfb --boot-args ${cfg} ${bfb} "${bfb_path}"/flat-cfg.bfb
       bfb="${bfb_path}"/flat-cfg.bfb
     fi
+  fi
+else
+  mkdir ${TMP_DIR}/bfb
+  bfb=$(basename "${bfb}")
+  bfb=${bfb%.*}
+  bfb_path=${TMP_DIR}/bfb/"${bfb}"/${psid}
+  bfb="${bfb_path}"/flat.bfb
+  if [ ! -e "${bfb}" ]; then
+    echo "Error: ${bfb} not found"
+    exit 1
+  fi
+  # Replace config file if provided.
+  if [ -n "${cfg}" -a -e "${cfg}" ]; then
+    mlx-mkbfb --boot-args ${cfg} ${bfb} "${bfb_path}"/flat-cfg.bfb
+    bfb="${bfb_path}"/flat-cfg.bfb
   fi
 fi
 
@@ -1045,7 +1084,23 @@ if [ -e "${bfb}" ]; then
   wait_for_update_to_finish
 fi
 
-# LFWP activation on PCIe host.
+
+# Set SP2.BIT6=1 to issue PLDM ActivateFirmware command that activate new images after reboot
+# For DPU mode, need to set SWINT2.BIT2 additionally.
+# Always reset the BITs before setting them
+
+clear_sp2_267_swint2_2
+
+sp2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 | awk '{print $3}'`
+sp2=$((sp2 | 64))
+echo "SP2 $sp2"
+${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 $sp2 >/dev/null
+# Set SWINT2.BIT2 for DPU mode
+if [ ${nic_mode} -eq 0 ]; then
+  ${BF_REG} $(basename ${rshim_node}) ${RSH_SWINT}.64 0x4 >/dev/null
+fi
+
+# LFWP activation(reset) on PCIe host.
 if [ ${apply_lfwp} -eq 1 ]; then
   if [ -z "${pcie_bd}" ]; then
     echo "ERROR: Failed to activate LFWP, PCIe device not found."
@@ -1057,14 +1112,6 @@ if [ ${apply_lfwp} -eq 1 ]; then
     exit 1
   fi
 
-  # Set SP2.BIT6=1 to issue PLDM ActivateFirmware command that activate new image after reboot
-  sp2=`${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 | awk '{print $3}'`
-  sp2=$((sp2 | 64))
-  ${BF_REG} $(basename ${rshim_node}) ${RSH_SCRATCHPAD2}.64 $sp2 >/dev/null
-  # Set SWINT2.BIT2 for DPU mode
-  if [ ${nic_mode} -eq 0 ]; then
-    ${BF_REG} $(basename ${rshim_node}) ${RSH_SWINT}.64 0x4 >/dev/null
-  fi
   # Best-effort to check and apply L0 reset.
   if (mlxfwreset -d ${pcie_bd}.0 q | grep live-Patch | grep -qw "\-Supported"); then
     echo "Live Patch NIC Firmware reset is supported."
